<?php

namespace App\Exceptions;

use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * The list of the inputs that are never flashed to the session on validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (Throwable $e) {
            //
        });
    }

    public function render($request, Throwable $e)
    {
        $msg = $e->getMessage();
        $code = $e->getCode() ? $e->getCode() : 422;
        //        dd(get_class($e));
        switch (get_class($e)){
            case MethodNotAllowedHttpException::class:
                $msg = '服务器内部错误,(您可能未使用https)';
                $code = 500;
                break;
        }
        return response()->json(['msg' => $msg], $code);
//        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
